### ISSUE TITLE
Day 15 of AoC 2021: index out of bounds

### ISSUE THREAD

**Issue by BigPeet** [Fadi88/AoC#2]
For some reason, when I tested your solution with my input I got an index out of bounds error.
I've looked a little more into it: Somehow the grid created ends up with 101 lines (one being empty).

I don't see any extra (empty) lines in my input, but I'm not that familiar with include_str.

[input.txt](https://github.com/Fadi88/AoC/files/7722550/input.txt)

**Comment by Fadi88** [comment]
seems that the input file has an extra empty line at the end 
add a fixes that ingores lines under 3 chars

**Comment by Fadi88** [comment]
![Screenshot from 2021-12-15 22-04-05](https://user-images.githubusercontent.com/6080387/146264778-9b1d4c88-a2c3-429b-b7d0-86027cf0c5a3.png)

**Comment by BigPeet** [comment]
Strange. This extra line is not present, when I open the file with any editor:

![no_extra_line](https://user-images.githubusercontent.com/1740244/146270466-81b07fd7-701c-4a64-b23c-bb4d681cd9f5.png)

Maybe it depends on the OS.

**Comment by Fadi88** [comment]
That is really strange, i just did a hexdump on the file and you are correct it only has one \n at the end which should produce similar results on linux/mac

also why some editors have different behavior while rust get smilar one 
the first screenshot i shared was from vs code on ubuntu 21.10 native, and this is the hexdump with a single line return from the same machine


![Screenshot from 2021-12-15 22-58-30](https://user-images.githubusercontent.com/6080387/146271607-c7cfc2e0-7e65-48e0-a760-bd55604939ef.png)

EDIT: in my input i dont have the last \n maybe some editors ignore it while some dont but the executable always sees it 
this is my input hexdumped
![Screenshot from 2021-12-15 23-06-32](https://user-images.githubusercontent.com/6080387/146272406-78fbc372-d7e1-428d-859e-c048787b7f6f.png)

**Comment by BigPeet** [comment]
According to these links  ([1](https://stackoverflow.com/a/729795), [2](https://unix.stackexchange.com/a/18789)) on Unix every line should end with a line break.

So the final \n should be "normal" and it's interesting how its handled so differently.
