### ISSUE TITLE
Need to sort list for solution 2?

### ISSUE THREAD

**Issue by baktak** [Fadi88/AoC#3]
Appreciate you posting the code - learning from it. 

Question: For the second problem I think you need to sort the list of calories before taking the sum of the last 3 as the problem set is looking for top 3? 

Adding cals.sort() before print(sum(cals[-3:])) gave me the correct answer. (not sure that's the most efficient way)

Note: I see you did include the sort function in your Rust version.

**Comment by Fadi88** [comment]
100% correct, thanks for the hint
must have been removed while cleaning it before pushing, putting it back again
